version: '3'

services:
  app:
    image: python:3.9
    container_name: python39-cosmos
    tty: true
    volumes:
      - ./src:/home/src
      - ./pip-lib:/pip-lib
    working_dir: "/home/src"
    environment:
      PYTHONUSERBASE: /pip-lib
  
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  
  scheduler:
    image: apache/airflow:2.0.0
    container_name: airflow-scheduler
    restart: always
    env_file:
      - ./config/airflow/repos/postgres/.env
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler

  webserver:
    image: apache/airflow:2.0.0
    container_name: airflow-webserver
    restart: on-failure
    env_file:
      - ./config/airflow/repos/postgres/.env
    ports:
      - 8080:8080
    depends_on:
      - scheduler
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    # command: db init # Use fist time only
    command: webserver # Using with docker-compose up after exec `db init`